# -*- coding: utf-8 -*-
"""cv lab5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-iA477EmkodczGONf00vlpdHHov_csp9
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

r_min = 100
r_max = 200

# Read the image
img = cv2.imread('/content/Jr-NTR.jpg')

# Convert to grayscale for simpler intensity slicing demonstration
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Initialize output images with zeros
slicing_with_bg = gray_img.copy() # Keeps original pixels outside range
slicing_without_bg = np.zeros_like(gray_img) # Sets pixels outside range to black

# Apply intensity slicing
for i in range(gray_img.shape[0]):
    for j in range(gray_img.shape[1]):
        pixel_value = gray_img[i, j]
        if r_min <= pixel_value <= r_max:
            # For slicing with background: keep original pixel, for slicing without: set to white
            slicing_without_bg[i, j] = 255
        else:
            # For slicing with background: set to black, for slicing without: keep black (0)
            slicing_with_bg[i, j] = 0

# Display the results
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB)) # Display original color image
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(slicing_with_bg, cmap='gray')
plt.title(f'Slicing with Background ({r_min}-{r_max})')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(slicing_without_bg, cmap='gray')
plt.title(f'Slicing without Background ({r_min}-{r_max})')
plt.axis('off')

plt.show()